### ISSUE TITLE
blogpost does not work due to pyscript update

### ISSUE THREAD

**Issue by hgbrian** [twiecki/pymc-in-browser#1]
Hi! I think the pyscript + pymc blogpost no longer works due to some change in pyscript. Tested on chrome and safari on mac os x.

From the console:
```Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.```

I think this fixes it:
```
from pyodide import create_proxy
@create_proxy
def on_click(evt):
```
Hope that helps!

**Comment by twiecki** [comment]
Thanks! Seems like that created a different problem though:

```
Failed to load resource: the server responded with a status of 404 ()
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pybutton.ts:52:24
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pybutton.ts:53:24
pybutton.ts:54 registered handlers
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:33:24
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:34:24
pyinputbox.ts:35 registered handlers
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:33:24
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:34:24
```

Do you have an idea?

**Comment by hgbrian** [comment]
Sorry, I cannot reproduce this error. I have only seen the "Failed to load resource" message in relation to the missing favicon.

Your current index.html works for me with no errors on OSX Chrome and Safari, whether I open it as a file or use `http.server`.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2780402/170843113-7da7f058-4bb1-4414-86c0-2d010f377b19.png">

**Comment by twiecki** [comment]
I host it on https://twiecki.io/pymc-in-browser.html and it fails for me there, does it work for you?

**Comment by hgbrian** [comment]
yes, it works the same there for me with chrome and safari
 is it possible your browser has an old pyscript cached or something? does it work incognito?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2780402/170869620-cd314a17-aef3-4ee2-a98b-6db1b2fd6293.png">

**Comment by twiecki** [comment]
Also no:
```
creating pyodide runtime
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pybutton.ts:52:24
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pybutton.ts:53:24
pybutton.ts:54 registered handlers
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:33:24
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:34:24
pyinputbox.ts:35 registered handlers
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:33:24
base.ts:143 TypeError: pyodide.runPythonAsync is not a function
    at HTMLElement.eval (base.ts:137:36)
    at pyinputbox.ts:34:24
```

**Comment by hgbrian** [comment]
Hmm, at least someone else had the same issue https://github.com/pyscript/pyscript/issues/147
It is also not reproducible across computers/browsers for them.

Confusingly, he solves it by changing `py-button` to `button`, but then also has to use `create_proxy`.
Sorry I can't really help debug here. It even works on a very old firefox i had lying around.

**Comment by twiecki** [comment]
@hgbrian That indeed fixes it for me -- thanks!
