### ISSUE TITLE
webapp is probably broken: no button

### ISSUE THREAD

**Issue by oort77** [twiecki/pymc-in-browser#2]
<img width="1913" alt="Screenshot 2022-06-06 at 13 41 01" src="https://user-images.githubusercontent.com/73858914/172146060-1d3f5507-c716-47ea-9bc5-cd30e78430fe.png">

**Comment by twiecki** [comment]
Ugh, thanks for reporting.

**Comment by twiecki** [comment]
Should be fixed with https://github.com/twiecki/pymc-in-browser/commit/96fb35ebe9deebb524914c1e9a447cb1b946e6c3.
